source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

use_frameworks!
inhibit_all_warnings!

abstract_target 'defaults' do

  pod 'SwiftLint', '~> 0.45.0'
  pod 'SwiftFormat/CLI', '~> 0.48.0'
  pod 'R.swift', '~> 5.4.0'

  # App

  target 'RickAndMorty'

end
